### PR TITLE
Need to mask off bit 7 which means the same?

### PR DESCRIPTION
**Pull request by folkertvanheusden**

### CODE REVIEW

**Comment by davidmoreno** [comment]
Commented at #55 .

I think, not sure, that if this bit is 0, it means this packet only has journal data.. so yes, it should be masked.

**Comment by davidmoreno** [comment]
Commented at #55 .

I think, not sure, that if this bit is 0, it means this packet only has journal data.. so yes, it should be masked.

But then we should also send it at rtppeer.cpp:454. That makes me think everybody ignores it, as we did not have problems here... AFAIK.

I accept this patch locally and update the mentioned line, and do some tests on my pi against a windows rtpmidi.

If all goes well, I merge the changes.

**Comment by folkertvanheusden** [comment]
> Commented at #55 .
> 
> I think, not sure, that if this bit is 0, it means this packet only has journal data.. so yes, it should be masked.
> 
> But then we should also send it at rtppeer.cpp:454. That makes me think everybody ignores it, as we did not have problems here... AFAIK.
> 
> I accept this patch locally and update the mentioned line, and do some tests on my pi against a windows rtpmidi.
> 
> If all goes well, I merge the changes.

Are you sure it is the journal?
Because I believe https://datatracker.ietf.org/doc/html/rfc6295#section-2.1 says it is about midi-data being in the data-section?
I noticed it as I set it in my test-implementation (because I would send a frame with midi in it).
I believe it is harmless to ignore as it seems redundant with the lower 7 bits info (0x61 means "this is midi").

**Comment by davidmoreno** [comment]
Yes, i think its harmless, but I'm not sure I'm sending the right code then. I want to test it a bit.

**Comment by davidmoreno** [comment]
I did some test sneding that bit to one, and at least rtpmidi on windows does not like it. nothing gets thought. Also it would need to be changed at rtpserver.cpp:186.

So I dont know if we are misreading it or something..

Do you think this affects in some way to the detected instabilities?

Anyway it will not harm, so its merged with the other detected 0x61, and a note for the why not send it.

**Pull request merged**
