### PR TITLE
added a few fmt::formatter types

### PR DESCRIPTION
**Pull request by sadguitarius**
Hi @davidmoreno, I was having trouble building with the most recent commit and it looks like others may have run into similar issues. Does this commit break anything for you? It seems like it's working fine for me so far. Thanks!

### CODE REVIEW

**Comment by sadguitarius** [comment]
Ok it's failing the CI test but it's working fine for me locally. I don't think anything I added would be causing that error but who knows? Can you take a look when you get a chance? Thanks!

**Comment by sadguitarius** [comment]
whoops I missed the other commit here, that probably fixes the same thing...

**Comment by davidmoreno** [comment]
Thanks!

I finally reimplemented them using `format_as`, that I didn't know before and makes formatting enums quite easy ( copilot gave me the final trick, using a macro, that makes it really easy). But thanks for the pointer.

For me it complied without any problems. What distro are you using?

I'm on Ubuntu 24.04.

**Comment by sadguitarius** [comment]
Oh cool, glad it all worked out! I really don't understand the fmt templates at all, just going through the compiler errors until it stops yelling at me, so I'm sure my solutions are less than ideal. I'm on Arch, which is currently on fmt 10.2.0.

**Comment by sadguitarius** [comment]
Oh I just checked out the `format_as` implementation, so much easier on the eyes!

**Pull request merged**
