### PR TITLE
Retry

### PR DESCRIPTION
**Pull request by folkertvanheusden**
UDP is not reliable, not even on ethernet (please see also the MSG_CONFIRM pull-request) so retry everything.

### CODE REVIEW

**Comment by davidmoreno** [comment]
I like the strings in a list idea, but not the change on behaviour.

The first failed at connection so does not create the alsa port, the second on fail will leave the alsa port dangling. 

The current behaviour is that if there is a CK timeout it will remove the client, which will close connections and so on. Or so is the theory, I suspect there may be something here. But anyway it should remove the client.

**Comment by folkertvanheusden** [comment]
What about keeping CK the same but only retrying regular timeout?

**Comment by davidmoreno** [comment]
Can you explain better? I do not understand the proposed solution.

**Comment by folkertvanheusden** [comment]
The problem is, you can't expect a UDP packet to reach its destiny. A switch' buffers may be full, the peer may be too busy, electronic glitches, tons of reasons.
So I think a few retries should be done before giving up.

**Comment by davidmoreno** [comment]
Code would not apply on current master. 

Please open a issue or another pull request. 

Thanks a lot anyway for the effort for creating this pull request.

**Pull request closed without merging**
