### PR TITLE
move mdns_rtpmidi to the library

### PR DESCRIPTION
**Pull request by folkertvanheusden**
As it is usefull for others.

### CODE REVIEW

**Comment by davidmoreno** [comment]
Also updated license at the files headers, as it is different for the library than the main program (apache2, gpl3).

I'm not totally sure that the mdns stuff should be in the library, but I certainly see the advantages.

**Comment by folkertvanheusden** [comment]
Thank you.

My reasoning was that the mdns part is a big part of the apple-midi, apart
from rtp-midi.

Brings me to a new point: maybe it would be useful to have some kind of cli
program or so or a rest-interface that allows you to add a ip-address +
port number of a rtp-midi system that does not do mdns.
I can give it a try if you like? Do you agree about rest-interface? Or
would you prefer a unix-domain socket solution of some sort?

Please note that I also see some instabilleties that I haven't figured out
yet: services disappearing and such.

regards

**Comment by davidmoreno** [comment]
There is a basic `rtpmidid-cli` that does just that. It uses unix sockets so its more or less secure (user must be part of rtpmidid group IIRC).

If you nail down where the instabilities are, please open a bug report so we can fix them!

Thanks a lot for all the work!

**Comment by folkertvanheusden** [comment]
The json-interface is perfect, maybe add a 'remove'.

**Pull request merged**
