### PR TITLE
Fix debian pkg

### PR DESCRIPTION
**Pull request by puck**
Hey,

Just a few little fixes to the Debian packaging.

Cheers

### CODE REVIEW

**Comment by davidmoreno** [comment]
Hi! Thanks!

I will recreate my packages later for double check it works, but all looks good.

One question, I see that you disable enable and start of the service, as you say its more compliant, but, is there a way to allow enable and restart? Maybe ask the user if it should be enabled and started?

For me if I install it is because I want it to be used, so its an extra step I prefer not to do. And I'm worried than less knowledgeable users will think its not working at all.

**Comment by puck** [comment]
Hey David,

My comment about being more compliant is because lintian complained about a bunch of things. :) I spotted that because I used sbuild to cross compile to armhf for deploying onto a Raspberry Pi.

By letting dh_installsystemd take care of installing the service file, it adds the start & enable commands to the postinst for you. It also creates a prerm that'll stop the daemon when the package is removed. If you have a look in the postinst/prerm that is deployed you'll see those changes.

Cheers,
Andrew

**Comment by davidmoreno** [comment]
Hi,

I just tried the generated package in a VM, and the service is not started:

```
root@suitable-sparrow:/tmp# systemctl status rtpmidid
○ rtpmidid.service
     Loaded: masked (Reason: Unit rtpmidid.service is masked.)
     Active: inactive (dead)
root@suitable-sparrow:/tmp# 
```

At `/var/lib/dpkg/info/rtpmidid.*` I only see the `postrm`, that does as you commented, but no `postinst`. 

```
root@suitable-sparrow:/tmp# ls /var/lib/dpkg/info/rtpmidid.*
/var/lib/dpkg/info/rtpmidid.list  /var/lib/dpkg/info/rtpmidid.postrm
root@suitable-sparrow:/tmp# 
```

Maybe there is something missing?

**Comment by davidmoreno** [comment]
Also, when doing a make deb, it looks all dates on the changelog are changed to current date.

**Comment by puck** [comment]
> Also, when doing a make deb, it looks all dates on the changelog are changed to current date.

Oh, I thought that was working correctly. Fixed now.

**Comment by puck** [comment]
> I just tried the generated package in a VM, and the service is not started:
> 
> ```
> root@suitable-sparrow:/tmp# systemctl status rtpmidid
> ○ rtpmidid.service
>      Loaded: masked (Reason: Unit rtpmidid.service is masked.)
>      Active: inactive (dead)
> root@suitable-sparrow:/tmp# 
> ```

Did you have a previous rtpmidid package installed? Does /etc/systemd/system/rtpmidid.service exist and contain anything? If it is a symlink, where does it point?

> At `/var/lib/dpkg/info/rtpmidid.*` I only see the `postrm`, that does as you commented, but no `postinst`.
> 
> ```
> root@suitable-sparrow:/tmp# ls /var/lib/dpkg/info/rtpmidid.*
> /var/lib/dpkg/info/rtpmidid.list  /var/lib/dpkg/info/rtpmidid.postrm
> root@suitable-sparrow:/tmp# 
> ```
> 
> Maybe there is something missing?

That's odd, this is what I see:

```
root@flick:/home/puck/personal/MIDI# ls -1 /var/lib/dpkg/info/rtpmidid*
/var/lib/dpkg/info/rtpmidid.list
/var/lib/dpkg/info/rtpmidid.md5sums
/var/lib/dpkg/info/rtpmidid.postinst
/var/lib/dpkg/info/rtpmidid.postrm
/var/lib/dpkg/info/rtpmidid.prerm
```

What is present in `debian/rtpmidid/DEBIAN/` in the git checkout for rtpmidid after your build the .debs?

**Comment by davidmoreno** [comment]
Hi,

I just updated how the version for the changelog is calculated and set.. its all in master. 

Now it is a script that parses and adds liens when needed. This fixes the hacky sed.. which for sure could be made to work, but was giving us problems.

**Comment by davidmoreno** [comment]
I checked again, was preparing a more complete report... and at logs I saw that I had not installed `avahi-daemon`.. Ithink this fixes all!

So I will merge, and add this dependency.

Thanks!

**Pull request merged**
